# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the jwt-1.0.0 branch
on:
  push:
    branches: [ jwt-1.0.0 ]
  pull_request:
    branches: [ jwt-1.0.0 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12' ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test_ci
